// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoesStore.Models;

#nullable disable

namespace ShoesStore.Migrations
{
    [DbContext(typeof(ShoesDbContext))]
    [Migration("20240530150423_notrangthaidongsp")]
    partial class notrangthaidongsp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chitietkhuyenmai", b =>
                {
                    b.Property<int>("Makm")
                        .HasColumnType("int")
                        .HasColumnName("MAKM");

                    b.Property<int>("Madongsanpham")
                        .HasColumnType("int")
                        .HasColumnName("MADONGSANPHAM");

                    b.HasKey("Makm", "Madongsanpham");

                    b.HasIndex(new[] { "Madongsanpham" }, "IX_CHITIETKHUYENMAI_MADONGSANPHAM");

                    b.HasIndex(new[] { "Makm" }, "IX_CHITIETKHUYENMAI_MAKM");

                    b.ToTable("CHITIETKHUYENMAI", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Banner", b =>
                {
                    b.Property<int>("Mabanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MABANNER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mabanner"));

                    b.Property<bool>("Hoatdong")
                        .HasColumnType("bit")
                        .HasColumnName("HOATDONG");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LINK");

                    b.Property<string>("Slogan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SLOGAN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Tenbanner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENBANNER");

                    b.Property<string>("Vitri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VITRI");

                    b.HasKey("Mabanner");

                    b.ToTable("Banner", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Binhluan", b =>
                {
                    b.Property<int>("Mabl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MABL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mabl"));

                    b.Property<int>("Madongsanpham")
                        .HasColumnType("int")
                        .HasColumnName("MADONGSANPHAM");

                    b.Property<int>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    b.Property<DateTime>("Ngaybl")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYBL");

                    b.Property<string>("Noidungbl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOIDUNGBL");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("RATING");

                    b.HasKey("Mabl");

                    b.HasIndex("Madongsanpham");

                    b.HasIndex("Makh");

                    b.ToTable("BINHLUAN", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Blog", b =>
                {
                    b.Property<int>("Mablog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MABLOG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mablog"));

                    b.Property<string>("Anhdaidien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOIDUNG");

                    b.Property<string>("Theloai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("THELOAI");

                    b.HasKey("Mablog");

                    b.HasIndex(new[] { "Manv" }, "IX_BLOG_MANV");

                    b.ToTable("BLOG", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Chitietphieumua", b =>
                {
                    b.Property<int>("Mapm")
                        .HasColumnType("int")
                        .HasColumnName("MAPM");

                    b.Property<int>("Maspsize")
                        .HasColumnType("int")
                        .HasColumnName("MASPSIZE");

                    b.Property<decimal>("Dongia")
                        .HasColumnType("money")
                        .HasColumnName("DONGIA");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Mapm", "Maspsize");

                    b.HasIndex(new[] { "Maspsize" }, "IX_CHITIETPHIEUMUA_IDCHITIETSP");

                    b.ToTable("CHITIETPHIEUMUA", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Dongsanpham", b =>
                {
                    b.Property<int>("Madongsanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADONGSANPHAM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madongsanpham"));

                    b.Property<decimal>("Giagoc")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("GIAGOC");

                    b.Property<int>("Maloai")
                        .HasColumnType("int")
                        .HasColumnName("MALOAI");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tendongsp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENDONGSP");

                    b.HasKey("Madongsanpham")
                        .HasName("PK__SANPHAM__B87C02A5C6299161");

                    b.HasIndex(new[] { "Maloai" }, "IX_DONGSANPHAM_MALOAI");

                    b.ToTable("DONGSANPHAM", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Khachhang", b =>
                {
                    b.Property<int>("Makh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makh"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENKH");

                    b.Property<decimal>("Tongxu")
                        .HasColumnType("money")
                        .HasColumnName("TONGXU");

                    b.HasKey("Makh")
                        .HasName("PK__KHACHHAN__B87DC1A73C57F8C5");

                    b.HasIndex(new[] { "Email" }, "IX_KHACHHANG_EMAIL")
                        .IsUnique();

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Khuyenmai", b =>
                {
                    b.Property<int>("Makm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makm"));

                    b.Property<DateTime>("Ngaybd")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYBD");

                    b.Property<DateTime>("Ngaykt")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYKT");

                    b.Property<int>("Phantramgiam")
                        .HasColumnType("int")
                        .HasColumnName("PHANTRAMGIAM");

                    b.HasKey("Makm");

                    b.ToTable("KHUYENMAI", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Loai", b =>
                {
                    b.Property<int>("Maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MALOAI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maloai"));

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("Maloai")
                        .HasName("PK__LOAI__0CDEF5199DDB5F30");

                    b.HasIndex(new[] { "Tenloai" }, "UQ__LOAI__BF45B996B528FC06")
                        .IsUnique();

                    b.ToTable("LOAI", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Mau", b =>
                {
                    b.Property<string>("Mamau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MAMAU");

                    b.Property<string>("Tenmau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENMAU");

                    b.HasKey("Mamau")
                        .HasName("PK__MAU__94185D28760C1F74");

                    b.ToTable("MAU", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Nhanvien", b =>
                {
                    b.Property<int>("Manv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manv"));

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tennv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNV");

                    b.HasKey("Manv")
                        .HasName("PK__NHANVIEN__B87DC9B274B84C76");

                    b.HasIndex(new[] { "Email" }, "IX_NHANVIEN_EMAIL")
                        .IsUnique();

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Phieumua", b =>
                {
                    b.Property<int>("Mapm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapm"));

                    b.Property<string>("Diachinguoinhan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHINGUOINHAN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Emailnguoinhan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAILNGUOINHAN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Lydohuydon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LYDOHUYDON");

                    b.Property<int?>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    b.Property<int?>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<int>("Mapttt")
                        .HasColumnType("int")
                        .HasColumnName("MAPTTT");

                    b.Property<string>("Mavoucher")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MAVOUCHER");

                    b.Property<DateTime>("Ngaydat")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYDAT");

                    b.Property<string>("Sdtnguoinhan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDTNGUOINHAN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Tennguoinhan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNGUOINHAN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Tinhtrang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TINHTRANG");

                    b.Property<decimal?>("Tongtien")
                        .HasColumnType("money")
                        .HasColumnName("TONGTIEN");

                    b.HasKey("Mapm")
                        .HasName("PK__PHIEUDAT__B87C5B0D30DC315E");

                    b.HasIndex("Mavoucher");

                    b.HasIndex(new[] { "Makh" }, "IX_PHIEUMUA_MAKH");

                    b.HasIndex(new[] { "Manv" }, "IX_PHIEUMUA_MANV");

                    b.HasIndex(new[] { "Mapttt" }, "IX_PHIEUMUA_MAPTTT");

                    b.ToTable("PHIEUMUA", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Phuong", b =>
                {
                    b.Property<int>("Maphuong")
                        .HasColumnType("int")
                        .HasColumnName("MAPHUONG");

                    b.Property<int>("Maquan")
                        .HasColumnType("int")
                        .HasColumnName("MAQUAN");

                    b.Property<string>("Tenphuong")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TENPHUONG");

                    b.HasKey("Maphuong");

                    b.HasIndex(new[] { "Maquan" }, "IX_PHUONG_MAQUAN");

                    b.ToTable("PHUONG", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Phuongthucthanhtoan", b =>
                {
                    b.Property<int>("Mapttt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPTTT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapttt"));

                    b.Property<string>("Tenphuongthuc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENPHUONGTHUC");

                    b.HasKey("Mapttt");

                    b.ToTable("PHUONGTHUCTHANHTOAN", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Quan", b =>
                {
                    b.Property<int>("Maquan")
                        .HasColumnType("int")
                        .HasColumnName("MAQUAN");

                    b.Property<int>("Matinh")
                        .HasColumnType("int")
                        .HasColumnName("MATINH");

                    b.Property<string>("Tenquan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TENQUAN");

                    b.HasKey("Maquan");

                    b.HasIndex(new[] { "Matinh" }, "IX_QUAN_MATINH");

                    b.ToTable("QUAN", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Sanpham", b =>
                {
                    b.Property<int>("Masp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masp"));

                    b.Property<string>("Anhdaidien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ANHDAIDIEN");

                    b.Property<string>("Anhdegiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ANHDEGIAY");

                    b.Property<string>("Anhmattren")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ANHMATTREN");

                    b.Property<int>("Madongsanpham")
                        .HasColumnType("int")
                        .HasColumnName("MADONGSANPHAM");

                    b.Property<string>("Mamau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MAMAU");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIDEO");

                    b.HasKey("Masp");

                    b.HasIndex("Mamau");

                    b.HasIndex(new[] { "Madongsanpham", "Mamau" }, "idx_unique_DongSp_Mau")
                        .IsUnique();

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Sanphamsize", b =>
                {
                    b.Property<int>("Maspsize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASPSIZE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maspsize"));

                    b.Property<int>("Masize")
                        .HasColumnType("int")
                        .HasColumnName("MASIZE");

                    b.Property<int>("Masp")
                        .HasColumnType("int")
                        .HasColumnName("MASP");

                    b.Property<int>("Slton")
                        .HasColumnType("int")
                        .HasColumnName("SLTON");

                    b.HasKey("Maspsize");

                    b.HasIndex("Masize");

                    b.HasIndex(new[] { "Masp", "Masize" }, "idx_unique_Sanpham_size")
                        .IsUnique();

                    b.ToTable("SANPHAMSIZE", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Size", b =>
                {
                    b.Property<int>("Masize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASIZE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masize"));

                    b.Property<string>("Tensize")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENSIZE");

                    b.HasKey("Masize")
                        .HasName("PK__SIZE__8DA14C4EB0779537");

                    b.ToTable("SIZE", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Sodiachi", b =>
                {
                    b.Property<int>("Masodiachi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASODIACHI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masodiachi"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DIACHI");

                    b.Property<int>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    b.Property<string>("Sdtnguoinhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDTNGUOINHAN");

                    b.Property<string>("Tennguoinhan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TENNGUOINHAN");

                    b.HasKey("Masodiachi");

                    b.HasIndex(new[] { "Makh" }, "IX_SODIACHI_MAKH");

                    b.ToTable("SODIACHI", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Taikhoan", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("Loaitk")
                        .HasColumnType("int")
                        .HasColumnName("LOAITK");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MATKHAU");

                    b.HasKey("Email")
                        .HasName("PK__TAIKHOAN__161CF7258466B7F4");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Tinh", b =>
                {
                    b.Property<int>("Matinh")
                        .HasColumnType("int")
                        .HasColumnName("MATINH");

                    b.Property<string>("Tentinh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TENTINH");

                    b.HasKey("Matinh");

                    b.ToTable("TINH", (string)null);
                });

            modelBuilder.Entity("ShoesStore.Models.Voucher", b =>
                {
                    b.Property<string>("Mavoucher")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MAVOUCHER");

                    b.Property<decimal>("Giamtoida")
                        .HasColumnType("money")
                        .HasColumnName("GIAMTOIDA");

                    b.Property<decimal>("Giatoithieu")
                        .HasColumnType("money")
                        .HasColumnName("GIATOITHIEU");

                    b.Property<DateTime>("Ngayhethan")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYHETHAN");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Mavoucher");

                    b.ToTable("VOUCHER", (string)null);
                });

            modelBuilder.Entity("Chitietkhuyenmai", b =>
                {
                    b.HasOne("ShoesStore.Models.Dongsanpham", null)
                        .WithMany()
                        .HasForeignKey("Madongsanpham")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETKHUYENMAI_DONGSANPHAM");

                    b.HasOne("ShoesStore.Models.Khuyenmai", null)
                        .WithMany()
                        .HasForeignKey("Makm")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETKHUYENMAI_KHUYENMAI");
                });

            modelBuilder.Entity("ShoesStore.Models.Binhluan", b =>
                {
                    b.HasOne("ShoesStore.Models.Dongsanpham", "MadongsanphamNavigation")
                        .WithMany("Binhluans")
                        .HasForeignKey("Madongsanpham")
                        .IsRequired()
                        .HasConstraintName("FK_BINHLUAN_DONGSANPHAM");

                    b.HasOne("ShoesStore.Models.Khachhang", "MakhNavigation")
                        .WithMany("Binhluans")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK_BINHLUAN_KHACHHANG");

                    b.Navigation("MadongsanphamNavigation");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Blog", b =>
                {
                    b.HasOne("ShoesStore.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Blogs")
                        .HasForeignKey("Manv")
                        .IsRequired()
                        .HasConstraintName("FK_BLOG_NHANVIEN");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Chitietphieumua", b =>
                {
                    b.HasOne("ShoesStore.Models.Phieumua", "MapmNavigation")
                        .WithMany("Chitietphieumuas")
                        .HasForeignKey("Mapm")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUMUA_PHIEUMUA");

                    b.HasOne("ShoesStore.Models.Sanphamsize", "MaspsizeNavigation")
                        .WithMany("Chitietphieumuas")
                        .HasForeignKey("Maspsize")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUMUA_SANPHAMSIZE");

                    b.Navigation("MapmNavigation");

                    b.Navigation("MaspsizeNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Dongsanpham", b =>
                {
                    b.HasOne("ShoesStore.Models.Loai", "MaloaiNavigation")
                        .WithMany("Dongsanphams")
                        .HasForeignKey("Maloai")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__IDLOAI__4222D4EF");

                    b.Navigation("MaloaiNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Khachhang", b =>
                {
                    b.HasOne("ShoesStore.Models.Taikhoan", "EmailNavigation")
                        .WithOne("Khachhang")
                        .HasForeignKey("ShoesStore.Models.Khachhang", "Email")
                        .IsRequired()
                        .HasConstraintName("FK__KHACHHANG__EMAIL__398D8EEE");

                    b.Navigation("EmailNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Nhanvien", b =>
                {
                    b.HasOne("ShoesStore.Models.Taikhoan", "EmailNavigation")
                        .WithOne("Nhanvien")
                        .HasForeignKey("ShoesStore.Models.Nhanvien", "Email")
                        .IsRequired()
                        .HasConstraintName("FK__NHANVIEN__EMAIL__3C69FB99");

                    b.Navigation("EmailNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Phieumua", b =>
                {
                    b.HasOne("ShoesStore.Models.Khachhang", "MakhNavigation")
                        .WithMany("Phieumuas")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK_PHIEUMUA_KHACHHANG");

                    b.HasOne("ShoesStore.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Phieumuas")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK__PHIEUDAT__IDNV__5441852A");

                    b.HasOne("ShoesStore.Models.Phuongthucthanhtoan", "MaptttNavigation")
                        .WithMany("Phieumuas")
                        .HasForeignKey("Mapttt")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUMUA_PHUONGTHUCTHANHTOAN");

                    b.HasOne("ShoesStore.Models.Voucher", "MavoucherNavigation")
                        .WithMany("Phieumuas")
                        .HasForeignKey("Mavoucher")
                        .HasConstraintName("FK_PHIEUMUA_VOUCHER");

                    b.Navigation("MakhNavigation");

                    b.Navigation("ManvNavigation");

                    b.Navigation("MaptttNavigation");

                    b.Navigation("MavoucherNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Phuong", b =>
                {
                    b.HasOne("ShoesStore.Models.Quan", "MaquanNavigation")
                        .WithMany("Phuongs")
                        .HasForeignKey("Maquan")
                        .IsRequired()
                        .HasConstraintName("FK_QUAN_PHUONG");

                    b.Navigation("MaquanNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Quan", b =>
                {
                    b.HasOne("ShoesStore.Models.Tinh", "MatinhNavigation")
                        .WithMany("Quans")
                        .HasForeignKey("Matinh")
                        .IsRequired()
                        .HasConstraintName("FK_QUAN_TINH");

                    b.Navigation("MatinhNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Sanpham", b =>
                {
                    b.HasOne("ShoesStore.Models.Dongsanpham", "MadongsanphamNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Madongsanpham")
                        .IsRequired()
                        .HasConstraintName("FK_SANPHAM_DONGSANPHAM");

                    b.HasOne("ShoesStore.Models.Mau", "MamauNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Mamau")
                        .IsRequired()
                        .HasConstraintName("FK_SANPHAM_MAU");

                    b.Navigation("MadongsanphamNavigation");

                    b.Navigation("MamauNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Sanphamsize", b =>
                {
                    b.HasOne("ShoesStore.Models.Size", "MasizeNavigation")
                        .WithMany("Sanphamsizes")
                        .HasForeignKey("Masize")
                        .IsRequired()
                        .HasConstraintName("FK_SANPHAMSIZE_SIZE");

                    b.HasOne("ShoesStore.Models.Sanpham", "MaspNavigation")
                        .WithMany("Sanphamsizes")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK_SANPHAMSIZE_SANPHAM");

                    b.Navigation("MasizeNavigation");

                    b.Navigation("MaspNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Sodiachi", b =>
                {
                    b.HasOne("ShoesStore.Models.Khachhang", "MakhNavigation")
                        .WithMany("Sodiachis")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK__KHACHHAG__SODIACHI__123213");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("ShoesStore.Models.Dongsanpham", b =>
                {
                    b.Navigation("Binhluans");

                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("ShoesStore.Models.Khachhang", b =>
                {
                    b.Navigation("Binhluans");

                    b.Navigation("Phieumuas");

                    b.Navigation("Sodiachis");
                });

            modelBuilder.Entity("ShoesStore.Models.Loai", b =>
                {
                    b.Navigation("Dongsanphams");
                });

            modelBuilder.Entity("ShoesStore.Models.Mau", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("ShoesStore.Models.Nhanvien", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Phieumuas");
                });

            modelBuilder.Entity("ShoesStore.Models.Phieumua", b =>
                {
                    b.Navigation("Chitietphieumuas");
                });

            modelBuilder.Entity("ShoesStore.Models.Phuongthucthanhtoan", b =>
                {
                    b.Navigation("Phieumuas");
                });

            modelBuilder.Entity("ShoesStore.Models.Quan", b =>
                {
                    b.Navigation("Phuongs");
                });

            modelBuilder.Entity("ShoesStore.Models.Sanpham", b =>
                {
                    b.Navigation("Sanphamsizes");
                });

            modelBuilder.Entity("ShoesStore.Models.Sanphamsize", b =>
                {
                    b.Navigation("Chitietphieumuas");
                });

            modelBuilder.Entity("ShoesStore.Models.Size", b =>
                {
                    b.Navigation("Sanphamsizes");
                });

            modelBuilder.Entity("ShoesStore.Models.Taikhoan", b =>
                {
                    b.Navigation("Khachhang");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("ShoesStore.Models.Tinh", b =>
                {
                    b.Navigation("Quans");
                });

            modelBuilder.Entity("ShoesStore.Models.Voucher", b =>
                {
                    b.Navigation("Phieumuas");
                });
#pragma warning restore 612, 618
        }
    }
}
